Refactor JMAP Client
ops-center/james-go-client pull request #14
Opened 2024-07-25 11:19 UTC by samiulsami

2024-07-25 11:42 UTC, Imtiaz246 requested changes

2024-07-25 11:42 UTC, Imtiaz246 commented on james/auth.go
> +	{ //TODO: remove this block of code
Remove these comments.

2024-07-25 11:42 UTC, Imtiaz246 commented on james/jmap.go
> +
Remove need these newlines.

2024-07-25 11:53 UTC, samiulsami commented on james/auth.go
> +	{ //TODO: remove this block of code
Fixed.

2024-07-25 11:53 UTC, samiulsami commented on james/jmap.go
> +
Fixed.

2024-07-30 05:44 UTC, Imtiaz246 requested changes

2024-07-30 05:44 UTC, Imtiaz246 commented on james/jmap.go
> +-----------------------------------------
Remove these comments

2024-07-30 05:44 UTC, Imtiaz246 commented on james/auth.go
> +		if token, ok := os.LookupEnv("INBOX_SERVER_TOKEN"); ok && len(token) > 0 {
Remove comment

2024-07-30 05:49 UTC, merged